updated buildandrun script

diff --git a/Day-09---Disk Fragmenter/bin/buildandrun b/Day-09---Disk Fragmenter/bin/buildandrun
--- a/Day-09---Disk Fragmenter/bin/buildandrun
+++ b/Day-09---Disk Fragmenter/bin/buildandrun
@@ -27,7 +27,17 @@ echo "  - running make:"
 make || { echo "--- BUILD AND RUN --- abort"; exit 1; }
 
 EXECUTABLE_NAME=$(pwd | awk -F'/' '{print "Aoc-" $(NF-1)}')
+EXECUTABLE_NAME=${EXECUTABLE_NAME:0:10}
 echo "  - running executable: '$EXECUTABLE_NAME'"
 echo ""
-../bin/$EXECUTABLE_NAME
+../bin/$EXECUTABLE_NAME || { echo ""; echo "--- BUILD AND RUN --- abort"; echo ""; exit 1; }
+#../bin/$EXECUTABLE_NAME
 
+
+#parent_dir=$(basename "$(dirname "$(realpath "$0")")")
+#first_five=${parent_dir:0:5}
+#first_six=
+#
+#echo "  - running executable: '$first_five"
+#echo "  - running executable: '$first_six"
+#
